# https://github.com/pascalgn/automerge-action
name: "Automerge"
on:
  workflow_run:
    workflows: ["Check_Build_Test"]
    types:
      - completed

jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      - id: automerge
        name: automerge
        uses: "pascalgn/automerge-action@v0.15.2"
        env:
          GITHUB_TOKEN: "${{ secrets.ACCESS_TOKEN }}"
          LOG: "DEBUG"
          MERGE_ERROR_FAIL: true
          MERGE_LABELS: ""
          MERGE_METHOD_LABEL_REQUIRED: false
          MERGE_FILTER_AUTHOR: "Dennis-Nedry-From-Jurassic-Park"
