name: "Cargo Check & Build & Test"

on:
  push:
    branches:
      - "*"
  pull_request:
  workflow_run:
    workflows:
      - "Security audit"
    branches:
      - "*"
    types: [completed]

env:
  CARGO_TERM_COLOR: always

jobs:
  check:
    name: check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: check
  coverage:
    name: code-coverage
    runs-on: ubuntu-latest
    needs:
      - check
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Run cargo-tarpaulin
        uses: actions-rs/tarpaulin@v0.1
        with:
          version: '0.15.0'
          args: '-- --test-threads 1'

      - name: Upload to codecov.io
        uses: codecov/codecov-action@v1.0.2
        with:
          token: ${{secrets.GITHUB_TOKEN}}

      - name: Archive code coverage results
        uses: actions/upload-artifact@v1
        with:
          name: code-coverage-report
          path: cobertura.xml

  build_and_test:
    name: build_and_test
    runs-on: ubuntu-latest
    needs:
      - check
      - coverage
    strategy:
      matrix:
        toolchain:
          - stable
          - nightly
    steps:
      - uses: actions/checkout@v2
      - run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
      - run: cargo build --verbose
      - run: cargo test --verbose

  checks_complete:
    name: Trigger automerge
    runs-on: ubuntu-latest
    needs:
      - check
      - coverage
      - build_and_test
    steps:
      - name: Trigger automerge
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          event-type: checks-complete
        if: github.event_name != 'push'