name: Security audit
on:
  pull_request:
    paths:
      - 'Cargo.lock'
  push:
    branches:
      - *
      - security-audit-rust
    paths:
      - 'Cargo.lock'
      - 'app/Cargo.toml'
      - 'module1/Cargo.toml'
      - 'module2/Cargo.toml'
      - '**/Cargo.toml'
      - '**/Cargo.lock'
jobs:
  security_audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/audit-check@v1.2.0
        with:
          token: ${{ secrets.TOKEN }}

